version: '3'
services:
  vuejs:
    image: node:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "npm install && npm rebuild esbuild && npm run dev -- --host 0.0.0.0"

  laravel:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: dbspotify
      DB_USERNAME: admin
      DB_PASSWORD: admin

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbspotify
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Puerto para phpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

volumes:
  db_data: